---
title: "Figures from: Vertebrate host availability and the thermal properties of mosquito-borne parasite transmission"
author: |
    | Kyle J.-M. Dahlin, Suzanne M. O'Regan, Barbara A. Han, 
    | John Paul Schmidt, John M. Drake
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  pdf_document:
    keep_tex: yes
    extra_dependencies: ["float"]
    includes:
      in_header: header.tex
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "doc") })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, cache = FALSE, warning = FALSE, fig.pos = "H",
  out.extra = ""
)
# Load Libraries----------------------------------------------------------------
library(tidyverse)
library(latex2exp)
library(reshape2)
library(cowplot)
library(viridis)
library(RColorBrewer)
library(MetBrewer)
library(here)
library(lemon)
library(zplyr) # from https://github.com/burchill/zplyr/ # only needed for placing text using absolute coordinates in contact comparison figure

# Plot settings ----

# !!! [] make sure all plots have font size set at 11 max, unless necessary

# Set theme
theme_set(theme_minimal(11))

# Helper function: adds a "point at infinity" for plots with infinite sigmaH
inf_skew_func <- function(df, skew, divide, n_rows_to_add) {
  # Get the largest value of log10(sigmaH) in the data frame
  max_log10sigmaH <- filter(df, is.finite(sigmaH)) %>%
    select(sigmaH) %>%
    max() %>%
    log10()

  # Define the gap dividing finite and infinite sigmaH
  infinite_divide <- 10^mean(log10(c(divide, skew)))

  # Create a proxy sigmaH variable that replaces Inf with the value of "skew"
  df <- mutate(df, sigmaH_proxy = ifelse(is.finite(sigmaH),
    sigmaH, skew
  ))

  # add more proxy sigmaH values to make a "spread" at Inf
  added_sigma_vals <- seq(divide, skew, length.out = n_rows_to_add)
  for (i in 1:n_rows_to_add) {
    bump_val <- 1 + 0.05 * (i - 1)
    temp <- filter(df, is.infinite(sigmaH)) %>%
      mutate(sigmaH_proxy = ifelse(is.finite(sigmaH), sigmaH,
        added_sigma_vals[i]
      ))
    df <- add_row(df, temp) %>% distinct()
  }
  return(df)
}

# Helper function: place legends in empty facets of plot grids
# Code by: Artem Sokolov, found here: https://stackoverflow.com/questions/54438495/shift-legend-into-empty-facets-of-a-faceted-plot-in-ggplot2
shift_legend <- function(p) {
  pnls <- cowplot::plot_to_gtable(p) %>%
    gtable::gtable_filter("panel") %>%
    with(setNames(grobs, layout$name)) %>%
    purrr::keep(~ identical(.x, zeroGrob()))

  if (length(pnls) == 0) stop("No empty facets in the plot")

  lemon::reposition_legend(p, "center", panel = names(pnls))
}

# Helper function: apply nice labels for pathosystems
pathosystem_labeller <- function(df) {
  df <- df %>%
    ungroup() %>%
    mutate(system_label = case_when(
      system_ID == "Aedes aegypti / DENV" ~ "(a) *Ae. aegypti* and DENV",
      system_ID == "Aedes aegypti / ZIKV" ~ "(b) *Ae. aegypti* and ZIKV",
      system_ID == "Aedes albopictus / DENV" ~ "(c&#41; *Ae. albopictus* and DENV",
      system_ID == "Anopheles gambiae / Plasmodium falciparum" ~ "(d) *An. gambiae* and *P. falciparum*",
      system_ID == "Culex quinquefasciatus / WNV" ~ "(e) *Cx. quinquefasciatus* and WNV"
    ))
  return(df)
}

# Load required data ----

# !!! [] make sure all data is getting loaded here

eps <- .Machine$double.eps

# Vector trait TPC data
data.Vec <- read_rds("results/VecTPC_vals.rds") %>%
  #
  pathosystem_labeller()
# R0 data
# !!! [] needs to be updated to include 1e-1, 1e0, 1e1
data.R0 <- read_rds("results/R0_vals.rds") %>%
  pathosystem_labeller()
# Topt data
data.Topt <- read_rds("results/Topt_vals.rds") %>%
  pathosystem_labeller()
# Critical thermal extrema data
data.CT <- read_rds("results/CT_vals.rds") %>%
  pathosystem_labeller()

# Configure data sets for plotting ----

## Get values of vector traits across samples
# Mean values
mean.Vec <- data.Vec %>%
  select(-c(mosquito_species, pathogen, muL, etaL)) %>%
  pivot_longer(cols = lf:V0, names_to = "variable", values_to = "value") %>%
  group_by(system_ID, Temperature, variable) %>%
  summarise(mean = mean(value), .groups = "keep") %>%
  ungroup() %>%
  pivot_wider(names_from = "variable", values_from = "mean") %>%
  mutate(etaL = rhoL / (deltaL + eps)) %>%
  mutate(muL = etaL - rhoL) %>%
  mutate(V0 = ifelse(sigmaV_f * deltaL < (1 / lf),
    0,
    KL * rhoL * lf * (1 - 1 / (lf * sigmaV_f * deltaL))
  ))
# Median values (this one is used more frequently)
median.Vec <- data.Vec %>%
  select(-c(mosquito_species, pathogen, muL, etaL)) %>%
  pivot_longer(cols = lf:V0, names_to = "variable", values_to = "value") %>%
  group_by(system_ID, Temperature, variable) %>%
  summarise(median = median(value), .groups = "keep") %>%
  ungroup() %>%
  pivot_wider(names_from = "variable", values_from = "median") %>%
  mutate(etaL = rhoL / (deltaL + eps)) %>%
  # Aquatic-stage mosquito mortality rate. This should be ~infinite if deltaL = 0
  mutate(muL = etaL - rhoL) %>%
  mutate(V0 = ifelse(sigmaV_f * deltaL < (1 / lf),
    0,
    KL * rhoL * lf * (1 - 1 / (lf * sigmaV_f * deltaL))
  ))

# Compute *mosquito* thermal tolerance range (minimum and maximum)
MosqThermRange_df <- median.Vec %>%
  pathosystem_labeller() %>%
  group_by(system_label) %>%
  filter(V0 > 0) %>%
  mutate(CTmin_V0 = min(Temperature)) %>%
  mutate(CTmax_V0 = max(Temperature)) %>%
  select(system_ID, system_label, CTmin_V0, CTmax_V0) %>%
  distinct()
```

# Figures

```{r fig-1_contact_comparison, dev = c('pdf','svg', 'png'), out.width='100%', fig.align='center', fig.height=5, fig.width=7, fig.align='center', fig.cap='\\label{fig:contact_comparison} A comparison of the Ross-Macdonald and Chitnis contact rate formulations.'}
# resolution setting
resolution <- 1E2

## Define the contact models
# For each model, there is a vector-to-host and host-to-vector term

# Bites per mosquito per day
vector_host_contact_func <- function(df) {
  with(as.list(df), {
    ret <- case_when(
      # Ross-Macdonald aka Reservoir frequency dependence
      model == "RM" ~ sigma_V,
      # Chitnis dynamic
      model == "CD" ~ sigma_V * sigma_H * H / (sigma_H * H + sigma_V * V)
    )
  })
}

# Bites per host per day
host_vector_contact_func <- function(df) {
  with(as.list(df), {
    ret <- case_when(
      # Ross-Macdonald aka Reservoir frequency dependence
      model == "RM" ~ sigma_V * V / H,
      # Chitnis dynamic
      model == "CD" ~ sigma_H * sigma_V * V / (sigma_H * H + sigma_V * V)
    )
  })
}

## Set up density ranges
host_density_range <- c(1E-1, 1E2)
host_fixed_value <- 50
host_density_vec <- sort(c(seq(host_density_range[1], host_density_range[2],
  length.out = resolution
), host_fixed_value))

vector_density_range <- c(0, 1E3)
vector_fixed_value <- 500
vector_density_vec <- sort(c(seq(vector_density_range[1], vector_density_range[2],
  length.out = resolution
), vector_fixed_value))

## Set other parameters
max_biting_rate <- 0.45
sigma_V <- max_biting_rate

host_annoyance_threshold <- 50
sigma_H <- host_annoyance_threshold

## Create contact dynamics dataframe
models <- c("RM", "CD")
names(models) <- c("Ross-Macdonald", "Chitnis dynamic")

contact_df <- expand.grid(
  H = host_density_vec,
  V = vector_density_vec,
  sigma_V = sigma_V,
  sigma_H = sigma_H,
  model = models
) %>%
  mutate("Transmission model" = names(model)) %>%
  mutate(bites_mosquito_time = vector_host_contact_func(.)) %>%
  mutate(bites_host_time = host_vector_contact_func(.)) %>%
  rename("Host population density" = H) %>%
  rename("Mosquito population density" = V) %>%
  rename("Bites per mosquito per day" = bites_mosquito_time) %>%
  rename("Bites per host per day" = bites_host_time)

## Put plots together:
new_df <- contact_df %>%
  filter(`Mosquito population density` == vector_fixed_value |
    `Host population density` == host_fixed_value) %>%
  filter(`Bites per host per day` < 1E3) %>%
  select(-sigma_V, -sigma_H, -model) %>%
  melt(
    id = c(
      "Transmission model", "Bites per mosquito per day",
      "Bites per host per day"
    ),
    value.name = "x_vals"
  ) %>%
  rename(x_vars = variable) %>%
  melt(id = c("Transmission model", "x_vars", "x_vals"), value.name = "y_vals") %>%
  rename(y_vars = variable) %>%
  filter(x_vals != host_fixed_value & x_vals != vector_fixed_value) %>%
  mutate(y_max = 1.05 * y_vals) %>%
  mutate(label = case_when(
    x_vars == "Host population density" & y_vars == "Bites per mosquito per day" ~ "(a)",
    x_vars == "Mosquito population density" & y_vars == "Bites per mosquito per day" ~ "(b)",
    x_vars == "Host population density" & y_vars == "Bites per host per day" ~ "(c)",
    x_vars == "Mosquito population density" & y_vars == "Bites per host per day" ~ "(d)"
  )) %>%
  distinct()

# x = Host population density, y = Bites per mosquito per day
plot_HD_MC <- new_df %>%
  filter(x_vars == "Host population density") %>%
  filter(y_vars == "Bites per mosquito per day") %>%
  ggplot(aes(x = x_vals, y = y_vals, colour = `Transmission model`)) +
  # curves:
  geom_path(size = 1) +
  geom_blank(aes(y = y_max)) +
  # plot labels
  geom_abs_text(aes(xpos = 0.08, ypos = 0.89, label = label),
    color = "black", show.legend = FALSE
  ) +
  # x-axis:
  scale_x_continuous(
    name = "",
    expand = expansion(mult = c(0, .025))
  ) +
  # y-axis:
  scale_y_continuous(
    name = "Bites per mosquito per day",
    expand = c(0, 0),
    limits = c(0, NA)
  )

# x = Mosquito population density, y = Bites per mosquito per day
plot_MD_MC <- new_df %>%
  filter(x_vars == "Mosquito population density") %>%
  filter(y_vars == "Bites per mosquito per day") %>%
  ggplot(aes(x = x_vals, y = y_vals, colour = `Transmission model`)) +
  # curves:
  geom_path(size = 1) +
  geom_blank(aes(y = y_max)) +
  # plot labels
  geom_abs_text(aes(xpos = 0.08, ypos = 0.89, label = label),
    color = "black", show.legend = FALSE
  ) +
  # x-axis:
  scale_x_continuous(
    name = "",
    expand = expansion(mult = c(0, .025))
  ) +
  # y-axis:
  scale_y_continuous(
    name = "",
    expand = c(0, 0),
    limits = c(0, NA)
  ) +
  # hide legend
  guides(color = FALSE)

# x = Mosquito population density, y = Bites per host per day
plot_MD_HC <- new_df %>%
  filter(x_vars == "Mosquito population density") %>%
  filter(y_vars == "Bites per host per day") %>%
  # x = density variables, y = contact rates
  ggplot(aes(x = x_vals, y = y_vals, colour = `Transmission model`)) +
  # curves:
  geom_path(size = 1) +
  geom_blank(aes(y = y_max)) +
  # plot labels
  geom_abs_text(aes(xpos = 0.08, ypos = 0.89, label = label),
    color = "black", show.legend = FALSE
  ) +
  # x-axis:
  scale_x_continuous(
    name = "Mosquito population density",
    expand = expansion(mult = c(0, .025))
  ) +
  # y-axis:
  scale_y_continuous(
    name = "",
    expand = c(0, 0),
    limits = c(0, NA)
  )

# x = Host population density, y = Bites per host per day
plot_HD_HC <- new_df %>%
  filter(x_vars == "Host population density") %>%
  filter(y_vars == "Bites per host per day") %>%
  # x = density variables, y = contact rates
  ggplot(aes(x = x_vals, y = y_vals, colour = `Transmission model`)) +
  # curves:
  geom_path(size = 1) +
  geom_blank(aes(y = y_max)) +
  # plot labels
  geom_abs_text(aes(xpos = 0.08, ypos = 0.89, label = label),
    color = "black", show.legend = FALSE
  ) +
  # x-axis:
  scale_x_continuous(
    name = "Host population density",
    expand = expansion(mult = c(0, .025))
  ) +
  # y-axis:
  scale_y_continuous(
    name = "Bites per host per day",
    expand = c(0, 0),
    limits = c(0, NA)
  ) +
  # hide legend
  guides(color = FALSE)

# Combine plots into a grid and remove legends
contact_plot <- plot_grid(
  plot_HD_MC + theme(legend.position = "none"),
  plot_MD_MC + theme(legend.position = "none"),
  plot_HD_HC + theme(legend.position = "none"),
  plot_MD_HC + theme(legend.position = "none")
)

# Set legend to bottom of grid
legend <- get_legend(
  plot_HD_MC +
    guides(color = guide_legend(nrow = 1)) +
    theme(legend.position = "bottom")
)

# Put together grid and legend
contact_plot <- plot_grid(contact_plot, legend, ncol = 1, rel_heights = c(1, .05))

# Plot
contact_plot
```

```{r fig-3_MosquitoThermalTraits, dev = c('pdf','svg', 'png'),  out.width='100%', fig.height=6, fig.width=9, fig.align='center', fig.cap='\\label{fig:MosquitoThermalTraits} Thermal performance curves for the mosquito and parasite traits used in our model. The range of temperatures is restricted to values where the immature development rate is positive. For traits that do not involve a parasite, *Aedes aegypti* with DENV and *Ae. aegypti* with ZIKV curves overlap.'}
## Set up plot dataframe
MosqThermTraits_df <- median.Vec %>%
  # Mortality rate
  mutate(muV = 1 / lf) %>%
  # Recruitment rate
  mutate(lambdaV = V0 * muV) %>%
  # Prob. of surviving EIP
  mutate(P_EIP = exp(-muV / etaV)) %>%
  # Prob. of larval survival
  # Select relevant traits and parameters
  select(Temperature, system_ID, sigmaV, sigmaV_f, rhoL, lf, deltaL, P_EIP, betaV) %>%
  # select(Temperature, system_ID, lambdaV, sigmaV, betaV, lf, P_EIP) %>%
  # Turn all columns except Temperature and system_ID into variables
  melt(id = c("Temperature", "system_ID")) %>%
  mutate(variable = factor(variable,
    levels = c("lf", "sigmaV", "sigmaV_f", "rhoL", "deltaL", "P_EIP", "betaV"),
    labels = c(
      TeX("(a) Adult lifespan: $1/\\mu_V$ (days)"),
      TeX("(b) Biting frequency: $\\sigma_V$ (day$^{-1}$)"),
      TeX("(c) Eggs per female per day: $\\sigma_V f$"),
      TeX("(d) Immature development rate: $\\rho_L$"),
      TeX("(e) Prob. of immature survival: $\\delta_L$"),
      TeX("(f) Prob. of surviving EIP: $\\theta_V$"),
      TeX("(g) Vector competence: $\\beta_V$")
    )
  )) %>%
  group_by(Temperature, system_ID)

# !!! [] be sure to use a consistent order for mosquito life history traits
# !!! [] be sure to use a consistent list of mosquito life history traits:
#         - adult lifespan (1/mu_V)
#         - biting frequency (sigma_V)
#         - eggs per female per day (sigma_V * f)
#         - immature development rate
#         - Pr(larval survival) (deltaL)
#         - Pr(surviving EIP) (theta_V)
#         - vector competence (beta_V)


MosqThermTraits_plot <- MosqThermTraits_df %>%
  # Set up plotting variables and theme
  # x = Temperature, y = trait value
  ggplot(mapping = aes(x = Temperature, y = value, group = system_ID)) +
  # Plot trait values:
  geom_line(aes(colour = system_ID), size = 1) +
  # x-axis:
  scale_x_continuous(
    name = "Temperature (°C)",
    expand = c(0, 0),
    limits = c(10, 35),
    breaks = seq(10, 36, 2)
  ) +
  # y-axis:
  scale_y_continuous(expand = c(0.05, 0)) +
  # color:
  scale_color_manual(
    name = "System:",
    values = met.brewer("Egypt", 5, direction = -1),
    labels = function(x) {
      case_when(
        x == "Aedes aegypti / DENV" ~ "*Aedes aegypti* and DENV",
        x == "Aedes aegypti / ZIKV" ~ "*Ae. aegypti* and ZIKV",
        x == "Aedes albopictus / DENV" ~ "*Aedes albopictus* and DENV",
        x == "Anopheles gambiae / Plasmodium falciparum" ~ "*Anopheles gambiae* and *Plasmodium falciparum*",
        x == "Culex quinquefasciatus / WNV" ~ "*Culex quinquefasciatus* and WNV"
      )
    }
  ) +
  # faceting:
  facet_wrap(~variable,
    nrow = 3, scales = "free",
    labeller = labeller(variable = label_parsed)
  ) +
  # legend:
  guides(color = guide_legend(override.aes = list(size = 4))) +
  # theme options:
  theme_minimal_vgrid(11) +
  theme(
    axis.title.y = element_blank(),
    legend.position = "bottom",
    legend.margin = margin(),
    legend.text = ggtext::element_markdown(),
    legend.direction = "vertical",
    legend.justification = "center",
    axis.title.x = element_text(hjust = 0.2),
    strip.text = element_text(
      face = "bold",
      hjust = 0
    )
  )

shift_legend(MosqThermTraits_plot)
```

```{r fig-4_R0_TPCs, dev = c('pdf','svg', 'png'),  message=FALSE, out.width='100%', fig.width=9, fig.height=6, fig.align='center', fig.cap='\\label{fig:R0_plots} ${R}_0$ as a function of temperature has the properties of a thermal performance curve (TPC): it is positive on a single bounded interval and has a unique maximum value.'}
# Plot R0 vs. temperature curves. One plot for each mosquito+pathogen pair.
# One curve for Ross-Macdonald, a few for Chitnis

# x-axes = temperature
# y-axes = R0 (normalized so that max(R0) = 1)
# plots = one for each mosquito+pathogen combination, "system_ID"
# curve 1 = Ross-Macdonald R0 (shape doesn't depend on KH)
# curves  = Chitnis dynamic R0,
#   - colour = value of KH. place it on a color scale in the bottom right corner

# R0 as a function of temperature, seperate curves across values of KH and sigmaH

# Plot R0 vs. temperature curves. One plot for each system
# One curve for Ross-Macdonald, a few for Chitnis

# x-axes = temperature
# y-axes = R0 (normalized so that max(R0) = 1)
# plots = one for each mosquito+pathogen combination, "system_ID"
# curve 1 = Ross-Macdonald R0 (shape doesn't depend on KH)
# curves  = Chitnis dynamic R0,
#   - colour = value of KH. place it on a color scale in the bottom right corner
newKH_vals <- unique(data.R0$KH)[seq(1, length(unique(data.R0$KH)), length.out = 21)]

data.R0_norm <- data.R0 %>%
  ungroup() %>%
  mutate(system_label = case_when(
    system_ID == "Aedes aegypti / DENV" ~ "(a) *Ae. aegypti* and DENV",
    system_ID == "Aedes aegypti / ZIKV" ~ "(b) *Ae. aegypti* and ZIKV",
    system_ID == "Aedes albopictus / DENV" ~ "(c\u200b) *Ae. albopictus* and DENV",
    system_ID == "Anopheles gambiae / Plasmodium falciparum" ~ "(d) *An. gambiae* and *P. falciparum*",
    system_ID == "Culex quinquefasciatus / WNV" ~ "(e) *Cx. quinquefasciatus* and WNV"
  )) %>%
  filter(KH %in% newKH_vals) %>%
  filter(variable == "R0") %>%
  select(-variable) %>%
  # normalize variables to have a maximum of 1
  group_by(system_ID, Model, sigmaH, KH) %>%
  # mutate(mean_norm = mean / max(mean)) %>%
  mutate(median_norm = median / max(median)) %>%
  # mutate(highHCI_norm = highHCI / max(median)) %>%
  # mutate(lowHCI_norm = lowHCI / max(median)) %>%
  arrange(system_ID, sigmaH, KH, Temperature, median_norm)


R0_plot <- ggplot(mapping = aes(x = Temperature, group = KH)) +
  # path of mean, normalized R0 as a function of temperature (finite sigmaH):
  geom_path(
    data = filter(data.R0_norm, sigmaH == 100),
    aes(y = median_norm, colour = KH, linetype = "finite"),
    lwd = 1
  ) +
  # path of mean, normalized R0 as a function of temperature (infinite sigmaH):
  geom_path(
    data = filter(data.R0_norm, sigmaH == Inf),
    aes(y = median_norm, linetype = "infinite", colour = "black"),
    colour = "black",
    lwd = 1.5
  ) +
  # # 89% HCI of R0 TPC curves
  # geom_ribbon(
  #   data = filter(data.R0_norm, sigmaH == 100),
  #   aes(ymin = lowHCI_norm, ymax = highHCI_norm, fill = KH),
  #   alpha = 0.1
  # ) +
  # x-axis:
  scale_x_continuous(
    name = "Temperature (°C)",
    expand = c(0, 0),
    limits = c(14, 34)
  ) +
  # y-axis:
  scale_y_continuous(
    name = TeX("Normalized $R_0$"),
    expand = c(0, .05)
  ) +
  # color: scaled log10, color-blind friendly
  scale_color_viridis(
    name = "Vertebrate host population\ndensity (ind/ha)",
    trans = "log10",
    breaks = 10^seq(-2, 4),
    labels = unname(c(0.01, 0.1, 1, 10, 100, TeX("$10^3$"), TeX("$10^4$"))),
    option = "plasma"
  ) +
  # fill: scaled log10, color-blind friendly
  scale_fill_viridis(
    name = "Vertebrate host population\ndensity (ind/ha)",
    trans = "log10",
    breaks = 10^seq(-2, 4),
    labels = unname(c(0.01, 0.1, 1, 10, 100, TeX("$10^3$"), TeX("$10^4$"))),
    option = "plasma"
  ) +
  # linetype:
  scale_linetype_manual(
    name = "Biting tolerance\n(bites per host per day)",
    breaks = c("finite", "infinite"),
    labels = unname(c(TeX("100 (Chitnis)"), TeX("$\\infty$ (Ross-Macdonald)"))),
    values = c("solid", "22")
  ) +
  # faceting:
  facet_wrap(~system_label, scales = "free", nrow = 2, labeller = labeller()) +
  # legend
  guides(
    color = guide_colourbar(
      title.position = "top",
      nrow = 1,
      barwidth = 12,
      show.limits = TRUE,
      direction = "horizontal"
    ),
    linetype = guide_legend(
      title.position = "top",
      nrow = 2,
      keywidth = 4,
      direction = "vertical"
    )
  ) +
  # theme options:
  theme_minimal_vgrid(16) +
  theme(
    legend.box = "vertical",
    legend.margin = margin(),
    legend.title = element_text(size = 10),
    legend.text = element_text(
      size = 10,
      hjust = 0
    ),
    legend.justification = "left",
    axis.title.x = element_text(hjust = 0.5),
    strip.text = ggtext::element_markdown(
      size = 11,
      hjust = 0,
      padding = margin(0, 0, 0, 0),
      margin = margin(1, 1, 1, 1)
    )
  )

# Plot
R0_plot <- shift_legend(R0_plot)
```

```{r fig-5_Topt, dev = c('pdf','svg', 'png'), message=FALSE, out.width='100%', fig.width=9, fig.height=6, fig.align='center', fig.cap='\\label{fig:Topt} The thermal optimum for transmission, $T_{opt}$, may be sensitive to vertebrate host population density and biting tolerance.'}
# Shows how the transmission thermal optimum depends on vertebrate host availability (density and biting tolerance) in each of the systems we consider.

#   x    = biting tolerance (with a point at infinity)
#   y    = vertebrate host population density
# colour = width of parasite thermal niche (CTmax - CTmin)
# Facets = systems

Toptalt_df <- data.Topt %>%
  ungroup() %>%
  mutate(system_label = case_when(
    system_ID == "Aedes aegypti / DENV" ~ "(a) *Ae. aegypti* and DENV",
    system_ID == "Aedes aegypti / ZIKV" ~ "(b) *Ae. aegypti* and ZIKV",
    system_ID == "Aedes albopictus / DENV" ~ "(c\u200b) *Ae. albopictus* and DENV",
    system_ID == "Anopheles gambiae / Plasmodium falciparum" ~ "(d) *An. gambiae* and *P. falciparum*",
    system_ID == "Culex quinquefasciatus / WNV" ~ "(e) *Cx. quinquefasciatus* and WNV"
  )) %>%
  distinct() %>%
  # Arrange along the plotting variables
  arrange(system_ID, sigmaH, KH, mean) %>%
  mutate(sigmaH_proxy = sigmaH)

# add many proxy sigmaH points at infinity to make the values easier to see there
max_sigmaH <- max(filter(Toptalt_df, is.finite(sigmaH))$sigmaH)
# Value of sigmaH to replace 'Inf' with for plotting
infinite_skew <- 10^2.35 # 10^log10(max_sigmaH*1.5) # 1.1*max_sigmaH #10^2 + 80
# Used to create a gap dividing finite and infinite sigmaH
infinite_divide <- 10^2.7 # 10^log10(max_sigmaH*1)

Toptalt_df <- inf_skew_func(Toptalt_df, infinite_skew, infinite_divide, 8)

# infinite_divide <- 10^mean(c(2, log10(infinite_skew)))

# Define sigmaH tick breaks and labels
sigmaH_breaks <- c(10^c(seq(-1, 2, by = 1)), 10^2.3125, 10^2.5625)
sigmaH_labels <- c(paste(c(10^c(seq(-1, 2, by = 1)))), TeX("$\\ldots$"), TeX("$\\infty$"))

min_Topt <- floor(min(min(Toptalt_df$mean), min(Toptalt_df$median)))
max_Topt <- ceiling(max(max(Toptalt_df$mean), max(Toptalt_df$median)))
Topt_breaks <- seq(min_Topt, max_Topt, by = 1)

# Plot mean of Topt heat map
Toptalt_plots <- Toptalt_df %>%
  ## Set up plot ##
  # x = biting tolerance (with a point at infinity),
  # y = vertebrate host population density,
  # color = transmission thermal optimum
  ggplot(aes(x = KH, y = sigmaH_proxy, z = median)) +
  # Topt for FINITE sigmaH:
  geom_contour_filled(
    data = filter(Toptalt_df, sigmaH_proxy < 10^2.2),
    breaks = Topt_breaks
  ) +
  # Topt for INFINITE sigmaH:
  # take mean of mean to hide variation from artifacts of uncertainty
  geom_contour_filled(
    data = filter(Toptalt_df, sigmaH_proxy > infinite_skew) %>%
      group_by(system_ID) %>%
      mutate(mean = mean(mean), .groups = "keep"),
    size = 1,
    breaks = Topt_breaks
  ) +
  # # R0 = 1 contour: cheat and use where CTwidth = 0 (i.e. where R0<1 at any temperature)
  geom_contour(
    data = filter(data.CT, variable == "CTwidth", sigmaH < infinite_divide),
    aes(y = sigmaH, z = mean, colour = "R0 = 1"),
    breaks = min(filter(data.CT, variable == "CTwidth", mean > 0)$mean),
    size = 1
  ) +
  # geom_contour(data = data.R0_norm,
  #              aes(y = sigmaH, z = mean, colour = "R0=1"), breaks = c(1), size = 1) +
  # x-axis: log10-scale with no buffer space
  scale_x_log10(
    name = TeX("Vertebrate host population density (ind/ha)"),
    expand = c(0, 0),
    limits = c(0.05, 1E4),
    breaks = 10^seq(-1, 4, 1),
    labels = TeX(c("$0.1$", "$1$", "$10", "$100$", "$10^3$", "$10^4$"))
  ) +
  # y-axis: log10-scale y axis, with no buffer space
  scale_y_log10(
    name = TeX("Biting tolerance (bites per host per day)"),
    expand = c(0, 0),
    breaks = sigmaH_breaks,
    labels = sigmaH_labels
  ) +

  # fill:
  scale_fill_manual(
    name = "Transmission thermal optimum (°C)",
    values = met.brewer("Johnson",
      n = length(Topt_breaks),
      direction = -1
    )
  ) +
  # color:
  scale_colour_manual(
    name = "",
    labels = c("R0=1" = unname(TeX("$\\mathcal{R}_0=1$"))),
    values = c("black"),
    guide = guide_legend(
      order = 1,
      keyheight = unit(1, "cm"),
      override.aes = list(size = 6)
    )
  ) +
  # faceting:
  facet_wrap(~system_label, scales = "free", nrow = 2, labeller = labeller()) +
  # legend:
  guides(fill = guide_coloursteps(
    title.position = "top", title.hjust = 0,
    barwidth = unit(7, "cm"),
    show.limits = TRUE
  )) +
  # theme options:
  theme_minimal(16) +
  theme(
    legend.box = "vertical",
    legend.position = "right",
    legend.margin = margin(0, 0, 0, 0),
    legend.title = element_text(size = 10),
    legend.direction = "horizontal",
    legend.justification = "left",
    axis.title.x = element_text(hjust = 0.5),
    strip.text = ggtext::element_markdown(
      size = 11,
      hjust = 0,
      padding = margin(0, 0, 0, 0),
      margin = margin(1, 1, 1, 1)
    )
  )

# Plot
Toptalt_plots <- shift_legend(Toptalt_plots)
```

```{r fig-6_CT_Width, dev = c('pdf','svg', 'png'), message=FALSE, out.width='100%', fig.width=9, fig.height=6, fig.align='center', fig.cap='\\label{fig:CT_Width} The parasite population thermal tolerance range, the range of temperatures at which parasite transmission is expected to persist, is widest when biting tolerance is high and vertebrate host population density is low.'}
# Shows how the parasite thermal niche (temperatures between CT_min and CT_max)
# depends on vertebrate host availability (density and biting tolerance) in each
# of the focal systems.

#   x    = biting tolerance (with a point at infinity)
#   y    = vertebrate host population density
# colour = width of parasite thermal niche (CTmax - CTmin)
# Facets = systems

CTwidth_df <- data.CT %>%
  ungroup() %>%
  mutate(system_label = case_when(
    system_ID == "Aedes aegypti / DENV" ~ "(a) *Ae. aegypti* and DENV",
    system_ID == "Aedes aegypti / ZIKV" ~ "(b) *Ae. aegypti* and ZIKV",
    system_ID == "Aedes albopictus / DENV" ~ "(c\u200b) *Ae. albopictus* and DENV",
    system_ID == "Anopheles gambiae / Plasmodium falciparum" ~ "(d) *An. gambiae* and *P. falciparum*",
    system_ID == "Culex quinquefasciatus / WNV" ~ "(e) *Cx. quinquefasciatus* and WNV"
  )) %>%
  filter(variable == "CTwidth") %>%
  # filter(sigmaH < 10^2.2) %>%
  mutate(sigmaH_proxy = sigmaH) %>%
  # Arrange along the plotting variables
  arrange(system_ID, KH, sigmaH_proxy, median) %>%
  ungroup()

CTwidth_df <- inf_skew_func(CTwidth_df, infinite_skew, infinite_divide, 8)

CTWidth_heat_plots <- CTwidth_df %>%
  ## Set up plot ##
  # x = biting tolerance (with a point at infinity),
  # y = vertebrate host population density,
  # color = width of parasite thermal mean_CTwidth
  ggplot(aes(x = KH, y = sigmaH_proxy, z = mean)) +
  # CTwidth for FINITE sigmaH:
  geom_contour_filled(data = filter(CTwidth_df, sigmaH_proxy < 10^2.2)) +
  # CTwidth for INFINITE sigmaH:
  geom_contour_filled(data = filter(
    CTwidth_df,
    sigmaH_proxy > 10^2.4,
    sigmaH_proxy < infinite_divide
  )) +
  # x-axis: log10-scale with no buffer space
  scale_x_log10(
    name = TeX("Vertebrate host population density (ind/ha)"),
    expand = c(0, 0),
    limits = c(0.05, 1E4),
    breaks = 10^seq(-1, 4, 1),
    labels = TeX(c("$0.1$", "$1$", "$10", "$100$", "$10^3$", "$10^4$"))
  ) +
  # y-axis: log10-scale y axis, with no buffer space
  scale_y_log10(
    name = TeX("Biting tolerance (bites per host per day)"),
    expand = c(0, 0),
    breaks = sigmaH_breaks,
    labels = sigmaH_labels
  ) +
  # color:
  scale_fill_viridis_d(
    name = "Parasite thermal tolerance\nrange width (°C)",
    option = "plasma"
  ) +
  # faceting:
  facet_wrap(~system_label, scales = "free", nrow = 2, labeller = labeller()) +
  # legend:
  guides(fill = guide_coloursteps(
    title.position = "top", title.hjust = 0.5,
    barwidth = unit(5, "cm"),
    show.limits = TRUE
  )) +
  # theme options:
  theme_minimal(16) +
  theme(
    legend.box = "horizontal",
    legend.position = "bottom",
    legend.margin = margin(0, 0, 0, 0),
    legend.title = element_text(size = 10),
    legend.direction = "horizontal",
    legend.justification = "left",
    axis.title.x = element_text(hjust = 0.5),
    strip.text = ggtext::element_markdown(
      size = 11,
      hjust = 0,
      padding = margin(0, 0, 0, 0),
      margin = margin(1, 1, 1, 1)
    )
  )

# Plot
CTWidth_heat_plots <- shift_legend(CTWidth_heat_plots)
```

<!-- # Supplementary Figures -->

<!-- ```{r fig-S1_R0_heatmap_plots_all, dev = c('pdf','svg', 'png'), message=FALSE, out.width='100%', fig.width=9, fig.height=11, fig.align='center', fig.cap='\\label{fig:R0_heatmap_plots_all} R0 heatmap expressing threshold (R0 = 1) as a contour and thermal optimum as ridges.'} -->
<!-- # Plot R0 vs. temperature and biting tolerance (sigmaH). One panel each for low, mid, high vert host pop density. -->

<!-- # x = vertebrate host biting tolerance (needs to vary from "zero" to "infinity") -->
<!-- # y = Temperature -->
<!-- # color = R0 -->
<!-- # curves: -->
<!-- #   R0 = 1 contour (black curve) -->
<!-- #   Topt (red curve) -->

<!-- # Facets: -->
<!-- # Rows = levels of vertebrate host population density -->
<!-- # Columns = two MBPT systems -->
<!-- # Total = 6 plots -->

<!-- ## Set up plot data frame -->
<!-- # We re-create the output data frame so that we can vary sigmaH correctly. -->
<!-- # We also drop the resolution of KH down to just three values -->
<!-- # Need to update functions so that sigmaH == Inf <~> Model == "Ross-Macdonald" -->

<!-- ## Configure data frame for plotting -->
<!-- R0_df <- data.R0 %>% -->
<!--   select(system_ID, system_label, Temperature, sigmaH, KH, median) %>% -->
<!--   rename(R0 = median) %>%  -->
<!--   # Consider only 3 values of KH (on a log10-scale) -->
<!--   filter(KH %in% c(1E-1, unique(data.R0$KH)[7], unique(data.R0$KH)[10])) %>% # !!! temporary. recalculate R0 with 1e-1, 1e0, 1e1 -->
<!--   # Choose a limited range of sigmaH values -->
<!--   filter(sigmaH > 10^0.5) %>% -->
<!--   # Group by plotting variables -->
<!--   group_by(system_ID, KH, sigmaH) %>% -->
<!--   # Calculate Topt (which.max requires grouping) -->
<!--   mutate(Topt = `Temperature`[which.max(R0)]) %>% -->
<!--   as_tibble() %>% -->
<!--   arrange(system_ID, sigmaH, Temperature) -->

<!-- ## Add a "point at infinity" for sigmaH -->
<!-- # Value of sigmaH to replace 'Inf' with for plotting -->
<!-- infinite_skew <- 10^3 + 2500 -->

<!-- # Get the largest value of log10(sigmaH) -->
<!-- max_log10sigmaH <- filter(R0_df, is.finite(sigmaH)) %>% -->
<!--   select(sigmaH) %>% -->
<!--   max() %>% -->
<!--   log10() -->

<!-- # Used to create a gap dividing finite and infinite sigmaH -->
<!-- infinite_divide <- 10^mean(c(3, log10(infinite_skew))) -->

<!-- # add a second proxy sigmaH point at infinity to make the values easier to see there -->
<!-- temp <- filter(R0_df, is.infinite(sigmaH)) %>% -->
<!--   mutate(sigmaH_proxy = ifelse(is.finite(sigmaH), sigmaH, 1.2 * infinite_divide)) -->
<!-- # Create a proxy sigmaH variable that replaces Inf with infinite_skew -->
<!-- R0_df <- mutate(R0_df, sigmaH_proxy = ifelse(is.finite(sigmaH), -->
<!--                                              sigmaH, infinite_skew -->
<!-- )) -->
<!-- R0_df <- add_row(R0_df, temp) %>% distinct() -->

<!-- ## Compute mosquito thermal tolerance range (minimum and maximum) -->
<!-- temp_MosqThermRange_df <- MosqThermRange_df %>% -->
<!--   select(system_label, CTmin_V0, CTmax_V0) -->

<!-- ## PLOTTING ## -->

<!-- ## Options -->
<!-- # Define sigmaH tick breaks and labels -->
<!-- sigmaH_breaks <- c(10^c(seq(-1, 3, by = 1)), infinite_divide, infinite_skew) -->
<!-- sigmaH_labels <- c(paste(c(10^c(seq(-1, 3, by = 1)))), TeX("$\\ldots$"), TeX("$\\infty$")) -->

<!-- # Labels for facet rows -->
<!-- R0_df$KH <- factor(R0_df$KH, levels = c(.1, 1, 10)) -->
<!-- mylabels <- as_labeller(c( -->
<!--   `0.1` = "0.1 vertebrate hosts / ha", -->
<!--   `1` = "1 vertebrate host / ha", -->
<!--   `10` = "10 vertebrate hosts / ha" -->
<!-- )) -->

<!-- # Breaks used to decide fill for the heat map -->
<!-- fill_breaks <- c(1, seq(5, 20, by = 5), Inf) -->

<!-- # Define colors for heat map so that values of R0>1 go from yellow to red -->
<!-- my.cols <- rev(c(rev(brewer.pal(length(fill_breaks) - 1, "YlOrRd")))) -->

<!-- ## PLOT ## -->
<!-- R0_plot <- R0_df %>% -->
<!--   ggplot(mapping = aes(x = sigmaH_proxy, y = Temperature, z = R0)) + -->

<!--   # Mosquito thermal tolerance range lines -->
<!--   geom_hline( -->
<!--     data = temp_MosqThermRange_df, -->
<!--     aes(yintercept = CTmin_V0, colour = "VTTR"), -->
<!--     lwd = 1.275 -->
<!--   ) + -->
<!--   geom_hline( -->
<!--     data = temp_MosqThermRange_df, -->
<!--     aes(yintercept = CTmax_V0, colour = "VTTR"), -->
<!--     lwd = 1.275 -->
<!--   ) + -->

<!--   # R0 contours for FINITE sigmaH: -->
<!--   geom_contour_filled( -->
<!--     data = filter(R0_df, sigmaH_proxy < infinite_divide**0.98), -->
<!--     breaks = fill_breaks -->
<!--   ) + -->

<!--   # R0 contours for INFINITE sigmaH: -->
<!--   geom_contour_filled( -->
<!--     data = filter(R0_df, sigmaH_proxy > infinite_divide**1.02), -->
<!--     breaks = fill_breaks -->
<!--   ) + -->

<!--   # R0 = 1 contour: -->
<!--   geom_contour(aes(colour = "R0=1"), breaks = c(1), size = 1) + -->

<!--   # Topt curve: -->
<!--   geom_line( -->
<!--     # data = filter(R0_df, R0>1), # uncomment to only display Topt when R0 exceeds one -->
<!--     mapping = aes( -->
<!--       x = sigmaH_proxy, -->
<!--       y = Topt, -->
<!--       colour = "Topt" -->
<!--     ), -->
<!--     lwd = 1, -->
<!--     linetype = 1 -->
<!--   ) + -->

<!--   # white lines breaking up finite/infinite sigmaH values -->
<!--   geom_vline( -->
<!--     aes(xintercept = 0.85 * infinite_divide), -->
<!--     colour = "white", -->
<!--     lwd = .8, -->
<!--     show.legend = FALSE -->
<!--   ) + -->
<!--   geom_vline( -->
<!--     aes(xintercept = infinite_divide), -->
<!--     colour = "white", -->
<!--     lwd = .8, -->
<!--     show.legend = FALSE -->
<!--   ) + -->
<!--   geom_vline( -->
<!--     aes(xintercept = 1.2 * infinite_divide), -->
<!--     colour = "white", -->
<!--     lwd = .8, -->
<!--     show.legend = FALSE -->
<!--   ) + -->

<!--   # x-axis: -->
<!--   scale_x_log10( -->
<!--     name = TeX("Vertebrate host biting tolerance (bites per host per day)"), -->
<!--     breaks = sigmaH_breaks, -->
<!--     labels = sigmaH_labels, -->
<!--     expand = c(0, 0) -->
<!--   ) + -->

<!--   # y-axis: -->
<!--   scale_y_continuous( -->
<!--     name = expression("Temperature "(degree * C)), -->
<!--     expand = c(0, 0), -->
<!--     limits = c(14, 36), -->
<!--     breaks = seq(10, 36, by = 2) -->
<!--   ) + -->

<!--   # color: -->
<!--   scale_colour_manual( -->
<!--     name = "", -->
<!--     labels = c( -->
<!--       "R0=1" = unname(TeX("$R_0=1$")), -->
<!--       "Topt" = "Transmission\nthermal\noptimum", -->
<!--       "VTTR" = "Mosquito\nthermal\ntolerance\nlimit" -->
<!--     ), -->
<!--     values = c("black", "purple", "grey"), -->
<!--     guide = guide_legend( -->
<!--       order = 1, -->
<!--       keyheight = unit(2, "cm"), -->
<!--       override.aes = list(size = 6) -->
<!--     ) -->
<!--   ) + -->

<!--   # fill: -->
<!--   scale_fill_manual( -->
<!--     name = TeX("$R_0$"), -->
<!--     values = my.cols, -->
<!--     guide = guide_colorsteps( -->
<!--       order = 2, -->
<!--       breaks = fill_breaks, -->
<!--       barheight = unit(8, "cm") -->
<!--     ) -->
<!--   ) + -->

<!--   # faceting: -->
<!--   facet_rep_grid( -->
<!--     rows = vars(system_label), -->
<!--     cols = vars(KH), -->
<!--     scales = "free_y", -->
<!--     labeller = labeller(.cols = mylabels), -->
<!--     repeat.tick.labels = "left" -->
<!--   ) + -->

<!--   # theme options: -->
<!--   theme_minimal_hgrid(11) + -->
<!--   theme( -->
<!--     axis.line = element_line(), -->
<!--     panel.spacing = unit(1, "lines"), -->
<!--     legend.text = element_text(size = 11), -->
<!--     legend.text.align = 0, -->
<!--     strip.text = ggtext::element_markdown( -->
<!--       size = 8, -->
<!--       hjust = 0 -->
<!--     ) -->
<!--   ) -->

<!-- # Plot it -->
<!-- R0_plot -->
<!-- ``` -->

<!-- ```{r fig-S2_Topt_plots_varyKH, dev = c('pdf','svg', 'png'), message=FALSE, out.width='100%', fig.width=9, fig.height=6, fig.align='center', fig.cap='\\label{fig:Topt_plots_varyKH} The thermal optimum for transmission, $T_{opt}$, may be sensitive to vertebrate host population density and biting tolerance.'} -->
<!-- Topt_df <- data.Topt %>%  -->
<!--   pivot_wider(id_cols = c("system_ID", "Model", "sigmaH", "KH"),  -->
<!--               names_from = variable, -->
<!--               values_from = c("mean", "median", "lowHCI", "highHCI"))  %>%  -->
<!--   right_join(read_rds("results/CT_vals.rds") %>%  -->
<!--                filter(variable == "CTwidth") %>%  -->
<!--                pivot_wider(id_cols = c("system_ID", "Model", "sigmaH", "KH"),  -->
<!--                            names_from = "variable", -->
<!--                            values_from = c("mean", "median", "lowHCI", "highHCI"))) %>%  -->
<!--   filter(sigmaH %in% c(1, 10, 100, Inf)) %>%  -->
<!--   # filter(mean_CTwidth>0) %>%  -->
<!--   select(-c(mean_CTwidth, median_CTwidth, lowHCI_CTwidth, highHCI_CTwidth)) %>% -->
<!--   rename(mean = mean_Topt, median = median_Topt, lowHCI = lowHCI_Topt,  -->
<!--          highHCI = highHCI_Topt) %>%  -->
<!--   # filter(KH > 0.01) %>% -->
<!--   # filter(sigmaH %in% 10^seq(0, 2) | is.infinite(sigmaH)) %>% -->
<!--   group_by(KH) %>% -->
<!--   # Arrange along the plotting variables -->
<!--   arrange(system_ID, KH, mean) %>% -->
<!--   arrange(sigmaH) %>% -->
<!--   ungroup() -->

<!-- # PLOTTING -->
<!-- Topt_plot <- Topt_df %>% -->
<!--   ## Set up plot ## -->
<!--   # color = sigmaH -->
<!--   ggplot(aes(x = KH, colour = as.factor(sigmaH))) + -->
<!--   # Topt curves: -->
<!--   geom_path(aes(y = median), lwd = 1) + -->
<!--   # # Add dotted lines showing 89% HCI limits -->
<!--   # geom_path(aes(y = lowHCI), linetype = "dashed") + -->
<!--   # geom_path(aes(y = highHCI), linetype = "dashed") + -->
<!--   # x-axis: log10 scale, no buffer space -->
<!--   scale_x_log10( -->
<!--     name = TeX("Vertebrate host population density (ind/ha)"), -->
<!--     expand = c(0, 0), -->
<!--     limits = c(0.01, 2E4), -->
<!--     breaks = 10^seq(-2, 4), -->
<!--     labels = TeX(c( -->
<!--       "0.01", "0.1", "$1$", "$10$", "$100$", "$10^3$", "$10^4$" -->
<!--     )) -->
<!--   ) + -->
<!--   # y-axis -->
<!--   scale_y_continuous( -->
<!--     name = expression("Thermal optimum "(degree * C)), -->
<!--     expand = c(0.05, 0.05), -->
<!--     limits = c(21,30.5), # mean: 21-31, median: 21-32 -->
<!--     breaks = seq(21,32, by = 1) -->
<!--   ) + -->
<!--   # color: -->
<!--   scale_colour_manual( -->
<!--     name = "Vertebrate host biting tolerance\n(bites per host per day)", -->
<!--     values = c(met.brewer("VanGogh3", 4, direction = 1), "black"), -->
<!--     # values = c(brewer.pal(9, "YlOrRd")[c(3, 5, 7)], "black"), -->
<!--     breaks = c(1, 10, 100, Inf), -->
<!--     labels = unname(c("1 (Chitnis)", "10 (Chitnis)", "100 (Chitnis)", TeX("$\\infty$ (Ross-Macdonald)"))) -->
<!--   ) + -->
<!--   scale_fill_manual( -->
<!--     name = "Vertebrate host biting tolerance\n(bites per host per day)", -->
<!--     values = c(met.brewer("VanGogh3", 4, direction = 1), "black"), -->
<!--     # values = c(brewer.pal(9, "YlOrRd")[c(3, 5, 7)], "black"), -->
<!--     breaks = c(1, 10, 100, Inf), -->
<!--     labels = unname(c("1 (Chitnis)", "10 (Chitnis)", "100 (Chitnis)", TeX("$\\infty$ (Ross-Macdonald)"))) -->
<!--   ) + -->
<!--   # faceting: -->
<!--   facet_wrap(~system_ID, nrow = 2, labeller = labeller()) + -->
<!--   # theme options: -->
<!--   theme_minimal(16) + -->
<!--   guides(color = guide_legend(override.aes = list(size = 4))) + -->
<!--   theme( -->
<!--     legend.position = "bottom", -->
<!--     legend.margin = margin(), -->
<!--     legend.direction = "vertical", -->
<!--     legend.title = element_text(size = 10), -->
<!--     legend.text = element_text( -->
<!--       size = 10, -->
<!--       hjust = 0 -->
<!--     ), -->
<!--     legend.justification = "left", -->
<!--     axis.title.x = element_text(hjust = 0.5), -->
<!--     strip.text = ggtext::element_markdown( -->
<!--       size = 11, -->
<!--       hjust = 0, -->
<!--       padding = margin(0, 0, 0, 0), -->
<!--       margin = margin(1, 1, 1, 1) -->
<!--     ) -->
<!--   ) -->


<!-- # Plot -->
<!-- Topt_plot <- shift_legend(Topt_plot) -->
<!-- ``` -->

<!-- ```{r fig-S3_Topt_plots, dev = c('pdf','svg', 'png'), message=FALSE, out.width='100%', fig.width=9, fig.height=8, fig.align='center', fig.cap='\\label{fig:Topt_plots} Transmission thermal optimum as a function of vertebrate host availability.'} -->

<!-- # x-axis = vertebrate host biting tolerance -->
<!-- # y-axis = thermal optimum -->
<!-- # color = vertebrate host population density -->

<!-- Topt_plot <- data.Topt %>%  -->
<!--   # filter(sigmaH %in% c(1, 10, 100, Inf)) %>%  -->
<!--   # Choose appropriate pop. dens. values and group -->
<!--   filter(KH %in% 10^seq(0, 3)) %>% -->
<!--   arrange(system_ID, KH, sigmaH, median) %>%  -->
<!--   ## Set up plot ## -->
<!--   # color = sigmaH -->
<!--   ggplot(aes(x = sigmaH, colour = as.factor(KH))) + -->
<!--   # Topt curves: -->
<!--   geom_path(aes(y = mean), lwd = 1) + -->
<!--   # # Dotted lines showing limits of 89% HCI -->
<!--   # geom_path(aes(y = lowHCI),linetype = "dashed") + -->
<!--   # geom_path(aes(y = highHCI),linetype = "dashed") + -->
<!--   # white lines breaking up finite/infinite sigmaH values: -->
<!--   geom_vline( -->
<!--     aes(xintercept = 0.95 * infinite_divide), -->
<!--     colour = "white", -->
<!--     lwd = .9, -->
<!--     show.legend = FALSE -->
<!--   ) + -->
<!--   geom_vline( -->
<!--     aes(xintercept = 1.05 * infinite_divide), -->
<!--     colour = "white", -->
<!--     lwd = .9, -->
<!--     show.legend = FALSE -->
<!--   ) + -->
<!--   geom_vline( -->
<!--     aes(xintercept = 1.15 * infinite_divide), -->
<!--     colour = "white", -->
<!--     lwd = .9, -->
<!--     show.legend = FALSE -->
<!--   ) + -->
<!--   # x-axis: Use a log10-scale with no buffer space -->
<!--   scale_x_log10( -->
<!--     name = TeX("Vertebrate host biting tolerance (bites per host per day)"), -->
<!--     expand = c(0, 0), -->
<!--     limits = c(0.5, 150), -->
<!--     breaks = sigmaH_breaks, -->
<!--     labels = sigmaH_labels -->
<!--   ) + -->
<!--   # y-axis -->
<!--   scale_y_continuous( -->
<!--     name = expression("Thermal optimum "(degree * C)), -->
<!--     expand = c(0.05, 0.05), -->
<!--     limits = c(21,31), # mean: 21-31, median: 21-32 -->
<!--     breaks = seq(21,32, by = 1) -->
<!--   ) + -->
<!--   # color: -->
<!--   scale_colour_manual( -->
<!--     name = "Vertebrate host population\ndensity (ind/ha)", -->
<!--     values = met.brewer("Hokusai3", 4, -->
<!--                         # option = "plasma" -->
<!--     )) + -->
<!--   scale_fill_manual( -->
<!--     name = "Vertebrate host population\ndensity (ind/ha)", -->
<!--     values = met.brewer("Hokusai3", 4, -->
<!--                         # option = "plasma" -->
<!--     )) + -->
<!--   # faceting: -->
<!--   facet_wrap(~system_ID, -->
<!--              scales = "free", -->
<!--              nrow = 2, -->
<!--              labeller = labeller()  ) + -->
<!--   # theme options: -->
<!--   theme_minimal(16) + -->
<!--   guides(color = guide_legend(override.aes = list(size = 4))) + -->
<!--   theme( -->
<!--     legend.position = "bottom", -->
<!--     legend.margin = margin(), -->
<!--     legend.direction = "vertical", -->
<!--     legend.title = element_text(size = 10), -->
<!--     legend.text = element_text( -->
<!--       size = 10, -->
<!--       hjust = 0 -->
<!--     ), -->
<!--     legend.justification = "left", -->
<!--     axis.title.x = element_text(hjust = 0.5), -->
<!--     strip.text = ggtext::element_markdown( -->
<!--       size = 11, -->
<!--       hjust = 0, -->
<!--       padding = margin(0, 0, 0, 0), -->
<!--       margin = margin(1, 1, 1, 1) -->
<!--     ) -->
<!--   ) -->


<!-- # Plot -->
<!-- Topt_plot <- shift_legend(Topt_plot) -->
<!-- ``` -->


<!-- ```{r fig-S4_CTmin, dev = c('pdf','svg', 'png'), dev="cairo_pdf", message=FALSE, out.width='100%', fig.width=9, fig.height=6, fig.align='center', fig.cap='\\label{fig:CTmin} Critical thermal minimum as a function of vertebrate host availability.'} -->
<!-- # Shows how the transmission thermal optimum depends on vertebrate host availability (density and biting tolerance) in each of the systems we consider. -->

<!-- #   x    = biting tolerance (with a point at infinity) -->
<!-- #   y    = vertebrate host population density -->
<!-- # colour = CTmin -->
<!-- # Facets = systems -->

<!-- CTmin_df <- data.CT %>% -->
<!--   filter(variable == "CTmin") %>%  -->
<!--   filter(is.finite(mean)) %>% -->
<!--   mutate(sigmaH_proxy = sigmaH) %>%  -->
<!--   # Arrange along the plotting variables -->
<!--   arrange(system_ID, KH, sigmaH_proxy, mean) %>%  -->
<!--   ungroup() -->

<!-- # add many third proxy sigmaH points at infinity to make the values easier to see there -->
<!-- temp <- filter(CTmin_df, is.infinite(sigmaH)) %>% -->
<!--   mutate(sigmaH_proxy = ifelse(is.finite(sigmaH), sigmaH, -->
<!--                                mean(c(1.25 * infinite_divide, infinite_skew)) -->
<!--   )) -->
<!-- temp2 <- filter(CTmin_df, is.infinite(sigmaH)) %>% -->
<!--   mutate(sigmaH_proxy = ifelse(is.finite(sigmaH), sigmaH, -->
<!--                                mean(c(1.15 * infinite_divide, infinite_skew)) -->
<!--   )) -->
<!-- temp3 <- filter(CTmin_df, is.infinite(sigmaH)) %>% -->
<!--   mutate(sigmaH_proxy = ifelse(is.finite(sigmaH), sigmaH, -->
<!--                                mean(c(1.05 * infinite_divide, infinite_skew)) -->
<!--   )) -->
<!-- temp4 <- filter(CTmin_df, is.infinite(sigmaH)) %>% -->
<!--   mutate(sigmaH_proxy = ifelse(is.finite(sigmaH), sigmaH, -->
<!--                                mean(c(1.3 * infinite_divide, infinite_skew)) -->
<!--   )) -->
<!-- temp5 <- filter(CTmin_df, is.infinite(sigmaH)) %>% -->
<!--   mutate(sigmaH_proxy = ifelse(is.finite(sigmaH), sigmaH, -->
<!--                                mean(c(1.2 * infinite_divide, infinite_skew)) -->
<!--   )) -->
<!-- temp6 <- filter(CTmin_df, is.infinite(sigmaH)) %>% -->
<!--   mutate(sigmaH_proxy = ifelse(is.finite(sigmaH), sigmaH, -->
<!--                                mean(c(1.1 * infinite_divide, infinite_skew)) -->
<!--   )) -->
<!-- temp7 <- filter(CTmin_df, is.infinite(sigmaH)) %>% -->
<!--   mutate(sigmaH_proxy = ifelse(is.finite(sigmaH), sigmaH, -->
<!--                                mean(c(infinite_divide, infinite_skew)) -->
<!--   )) -->

<!-- CTmin_df <- add_row(CTmin_df, temp) -->
<!-- CTmin_df <- add_row(CTmin_df, temp2) -->
<!-- CTmin_df <- add_row(CTmin_df, temp3) -->
<!-- CTmin_df <- add_row(CTmin_df, temp4) -->
<!-- CTmin_df <- add_row(CTmin_df, temp5) -->
<!-- CTmin_df <- add_row(CTmin_df, temp6) -->
<!-- CTmin_df <- add_row(CTmin_df, temp7) %>% -->
<!--   arrange(sigmaH_proxy) %>% -->
<!--   distinct() -->

<!-- CTmin_heat_plots <- CTmin_df %>% -->
<!--   ## Set up plot ## -->
<!--   # x = biting tolerance (with a point at infinity), -->
<!--   # y = vertebrate host population density, -->
<!--   # color = width of parasite thermal mean_CTwidth -->
<!--   ggplot(aes(x = KH, y = sigmaH_proxy, z = median)) + -->

<!--   # CTmin for FINITE sigmaH: -->
<!--   geom_contour_filled( -->
<!--     data = filter(CTmin_df, sigmaH_proxy < 100) -->
<!--   ) + -->

<!--   # CTmin for INFINITE sigmaH: -->
<!--   geom_contour_filled( -->
<!--     data = filter(CTmin_df, is.infinite(sigmaH)) -->
<!--   ) + -->

<!--   # x-axis: log10-scale with no buffer space -->
<!--   scale_x_log10( -->
<!--     name = TeX("Vertebrate host population density (ind/ha)"), -->
<!--     expand = c(0, 0), -->
<!--     limits = c(0.05, 1E4), -->
<!--     breaks = 10^seq(-1, 4, 1), -->
<!--     labels = TeX(c("$0.1$", "$1$", "$10", "$100$", "$10^3$", "$10^4$")) -->
<!--   ) + -->
<!--   # y-axis: log10-scale y axis, with no buffer space -->
<!--   scale_y_log10( -->
<!--     name = TeX("Biting tolerance (bites per host per day)"), -->
<!--     expand = c(0, 0), -->
<!--     breaks = sigmaH_breaks, -->
<!--     labels = sigmaH_labels -->
<!--   ) + -->
<!--   # color: -->
<!--   scale_fill_viridis_d( -->
<!--     name = "Mean critical thermal minimum (°C)", -->
<!--     option = "plasma" -->
<!--   ) + -->
<!--   # faceting: -->
<!--   facet_wrap(~system_ID, scales = "free", nrow = 2, labeller = labeller()) + -->
<!--   # legend: -->
<!--   guides(fill = guide_coloursteps( -->
<!--     title.position = "top", title.hjust = 0.5, -->
<!--     barwidth = unit(10, "cm"), -->
<!--     show.limits = TRUE -->
<!--   )) + -->
<!--   # theme options: -->
<!--   theme_minimal(16) + -->
<!--   theme( -->
<!--     legend.box = "horizontal", -->
<!--     legend.position = "bottom", -->
<!--     legend.margin = margin(0, 0, 0, 0), -->
<!--     legend.title = element_text(size = 10), -->
<!--     legend.direction = "horizontal", -->
<!--     legend.justification = "left", -->
<!--     axis.title.x = element_text(hjust = 0.5), -->
<!--     strip.text = ggtext::element_markdown( -->
<!--       size = 11, -->
<!--       hjust = 0, -->
<!--       padding = margin(0, 0, 0, 0), -->
<!--       margin = margin(1, 1, 1, 1) -->
<!--     ) -->
<!--   ) -->

<!-- # Plot -->
<!-- CTmin_heat_plots <- shift_legend(CTmin_heat_plots) -->
<!-- ``` -->

<!-- ```{r fig-S5_CTmax, dev = c('pdf','svg', 'png'), dev="cairo_pdf", message=FALSE, out.width='100%', fig.width=9, fig.height=6, fig.align='center', fig.cap='\\label{fig:CTmax} Critical thermal maximum as a function of vertebrate host availability.'} -->

<!-- # Shows how the transmission thermal optimum depends on vertebrate host availability (density and biting tolerance) in each of the systems we consider. -->

<!-- #   x    = biting tolerance (with a point at infinity) -->
<!-- #   y    = vertebrate host population density -->
<!-- # colour = CTmax -->
<!-- # Facets = systems -->

<!-- CTmax_df <- read_rds("results/CT_vals.rds") %>% -->
<!--   filter(variable == "CTmax") %>%  -->
<!--   filter(is.finite(mean)) %>% -->
<!--   mutate(sigmaH_proxy = sigmaH) %>%  -->
<!--   # Arrange along the plotting variables -->
<!--   arrange(system_ID, KH, sigmaH_proxy, mean) %>%  -->
<!--   ungroup() -->

<!-- # add many third proxy sigmaH points at infinity to make the values easier to see there -->
<!-- temp <- filter(CTmax_df, is.infinite(sigmaH)) %>% -->
<!--   mutate(sigmaH_proxy = ifelse(is.finite(sigmaH), sigmaH, -->
<!--                                mean(c(1.25 * infinite_divide, infinite_skew)) -->
<!--   )) -->
<!-- temp2 <- filter(CTmax_df, is.infinite(sigmaH)) %>% -->
<!--   mutate(sigmaH_proxy = ifelse(is.finite(sigmaH), sigmaH, -->
<!--                                mean(c(1.15 * infinite_divide, infinite_skew)) -->
<!--   )) -->
<!-- temp3 <- filter(CTmax_df, is.infinite(sigmaH)) %>% -->
<!--   mutate(sigmaH_proxy = ifelse(is.finite(sigmaH), sigmaH, -->
<!--                                mean(c(1.05 * infinite_divide, infinite_skew)) -->
<!--   )) -->
<!-- temp4 <- filter(CTmax_df, is.infinite(sigmaH)) %>% -->
<!--   mutate(sigmaH_proxy = ifelse(is.finite(sigmaH), sigmaH, -->
<!--                                mean(c(1.3 * infinite_divide, infinite_skew)) -->
<!--   )) -->
<!-- temp5 <- filter(CTmax_df, is.infinite(sigmaH)) %>% -->
<!--   mutate(sigmaH_proxy = ifelse(is.finite(sigmaH), sigmaH, -->
<!--                                mean(c(1.2 * infinite_divide, infinite_skew)) -->
<!--   )) -->
<!-- temp6 <- filter(CTmax_df, is.infinite(sigmaH)) %>% -->
<!--   mutate(sigmaH_proxy = ifelse(is.finite(sigmaH), sigmaH, -->
<!--                                mean(c(1.1 * infinite_divide, infinite_skew)) -->
<!--   )) -->
<!-- temp7 <- filter(CTmax_df, is.infinite(sigmaH)) %>% -->
<!--   mutate(sigmaH_proxy = ifelse(is.finite(sigmaH), sigmaH, -->
<!--                                mean(c(infinite_divide, infinite_skew)) -->
<!--   )) -->

<!-- CTmax_df <- add_row(CTmax_df, temp) -->
<!-- CTmax_df <- add_row(CTmax_df, temp2) -->
<!-- CTmax_df <- add_row(CTmax_df, temp3) -->
<!-- CTmax_df <- add_row(CTmax_df, temp4) -->
<!-- CTmax_df <- add_row(CTmax_df, temp5) -->
<!-- CTmax_df <- add_row(CTmax_df, temp6) -->
<!-- CTmax_df <- add_row(CTmax_df, temp7) %>% -->
<!--   arrange(sigmaH_proxy) %>% -->
<!--   distinct() -->

<!-- min_CTmax <- floor(min(min(CTmax_df$mean),min(CTmax_df$median))) -->
<!-- max_CTmax <- ceiling(max(max(CTmax_df$mean),max(CTmax_df$median))) -->
<!-- CTmax_breaks <- seq(min_CTmax, max_CTmax, by = 1) -->

<!-- CTmax_heat_plots <- CTmax_df %>% -->
<!--   ## Set up plot ## -->
<!--   # x = biting tolerance (with a point at infinity), -->
<!--   # y = vertebrate host population density, -->
<!--   # color = CTmax -->
<!--   ggplot(aes(x = KH, y = sigmaH_proxy, z = median)) + -->
<!--   # CTmax for FINITE sigmaH: -->
<!--   geom_contour_filled( -->
<!--     data = filter(CTmax_df, sigmaH_proxy < 100) -->
<!--   ) + -->

<!--   # CTmax for INFINITE sigmaH: -->
<!--   geom_contour_filled( -->
<!--     data = filter(CTmax_df, is.infinite(sigmaH)) -->
<!--   ) + -->
<!--   # x-axis: log10-scale with no buffer space -->
<!--   scale_x_log10( -->
<!--     name = TeX("Vertebrate host population density (ind/ha)"), -->
<!--     expand = c(0, 0), -->
<!--     limits = c(0.05, 1E4), -->
<!--     breaks = 10^seq(-1, 4, 1), -->
<!--     labels = TeX(c("$0.1$", "$1$", "$10", "$100$", "$10^3$", "$10^4$")) -->
<!--   ) + -->
<!--   # y-axis: log10-scale y axis, with no buffer space -->
<!--   scale_y_log10( -->
<!--     name = TeX("Biting tolerance (bites per host per day)"), -->
<!--     expand = c(0, 0), -->
<!--     breaks = sigmaH_breaks, -->
<!--     labels = sigmaH_labels -->
<!--   ) + -->
<!--   # color: -->
<!--   scale_fill_viridis_d( -->
<!--     name = "Mean critical thermal maximum (°C)", -->
<!--     option = "plasma" -->
<!--   ) + -->
<!--   # faceting: -->
<!--   facet_wrap(~system_ID, scales = "free", nrow = 2, labeller = labeller()) + -->
<!--   # legend: -->
<!--   guides(fill = guide_coloursteps( -->
<!--     title.position = "top", title.hjust = 0.5, -->
<!--     barwidth = unit(10, "cm"), -->
<!--     show.limits = TRUE -->
<!--   )) + -->
<!--   # theme options: -->
<!--   theme_minimal(16) + -->
<!--   theme( -->
<!--     legend.box = "horizontal", -->
<!--     legend.position = "bottom", -->
<!--     legend.margin = margin(0, 0, 0, 0), -->
<!--     legend.title = element_text(size = 10), -->
<!--     legend.direction = "horizontal", -->
<!--     legend.justification = "left", -->
<!--     axis.title.x = element_text(hjust = 0.5), -->
<!--     strip.text = ggtext::element_markdown( -->
<!--       size = 11, -->
<!--       hjust = 0, -->
<!--       padding = margin(0, 0, 0, 0), -->
<!--       margin = margin(1, 1, 1, 1) -->
<!--     ) -->
<!--   ) -->

<!-- # Plot -->
<!-- CTmax_heat_plots <- shift_legend(CTmax_heat_plots) -->
<!-- ``` -->



<!-- ```{r fig-S6_CT_Range, dev = c('pdf','svg', 'png'), message=FALSE, out.width='100%', fig.width=9, fig.height=6, fig.align='center', fig.cap='\\label{fig:CT_Range} Parasite thermal niche as a function of vertebrate host population density and biting tolerance.'} -->
<!-- # x-axis = vertebrate host population density -->
<!-- # y-axis = Temperature -->
<!-- # linetype = biting tolerance -->
<!-- # colour = CT_min (blue), CT_max (red) -->

<!-- CTRange_df <- ThermPathChars %>% -->
<!--   # Arrange along the plotting variables -->
<!--   select(system_label, sigmaH, KH, CTmax, CTmin) %>% -->
<!--   # Choose a few sigmaH values to plot, including Inf -->
<!--   filter(sigmaH %in% c(10, 50, Inf)) %>% -->
<!--   group_by(KH) %>% -->
<!--   # Arrange along the plotting variables -->
<!--   arrange(system_label, KH, sigmaH, CTmax, CTmin) %>% -->
<!--   ungroup() %>% -->
<!--   melt(id = c("system_label", "KH", "sigmaH")) %>% -->
<!--   arrange(KH, sigmaH) -->

<!-- CTRange_plots <- CTRange_df %>% -->
<!--   ## Set up plot ## -->
<!--   # x-axis = population density, y-axis = temperature, -->
<!--   # color = thermal extrema, linetype = sigmaH -->
<!--   ggplot(aes( -->
<!--     x = KH, y = value, -->
<!--     linetype = as.factor(sigmaH), color = variable -->
<!--   )) + -->

<!--   # Mosquito thermal tolerance range lines -->
<!--   geom_hline( -->
<!--     data = MosqThermRange_df, -->
<!--     aes(yintercept = CTmin_V0, colour = "VTTR"), -->
<!--     lwd = 1.275 -->
<!--   ) + -->
<!--   geom_hline( -->
<!--     data = MosqThermRange_df, -->
<!--     aes(yintercept = CTmax_V0, colour = "VTTR"), -->
<!--     lwd = 1.275 -->
<!--   ) + -->

<!--   # Curves showing CTmin and CTmax -->
<!--   geom_path( -->
<!--     data = filter(CTRange_df, variable == "CTmin"), -->
<!--     lwd = 1 -->
<!--   ) + -->
<!--   geom_path( -->
<!--     data = filter(CTRange_df, variable == "CTmax"), -->
<!--     lwd = 1 -->
<!--   ) + -->

<!--   # x-axis: log10-scale with no buffer space -->
<!--   scale_x_log10( -->
<!--     name = TeX("Vertebrate host population density (ind/ha)"), -->
<!--     expand = c(0, 0), -->
<!--     limits = c(1E-2, 1E5), -->
<!--     breaks = 10^seq(-1, 4), -->
<!--     labels = TeX(c("$0.1$", "$1$", "$10$", "$100$", "$10^3$", "$10^4$")) -->
<!--   ) + -->
<!--   # y-axis: small buffer space -->
<!--   scale_y_continuous( -->
<!--     name = expression("Temperature "(degree * C)), -->
<!--     expand = c(0.05, 0.05), -->
<!--     limits = range(CTRange_df$value, na.rm = TRUE), -->
<!--     breaks = seq(floor(range(CTRange_df$value, na.rm = TRUE)[1]), -->
<!--                  floor(range(CTRange_df$value, na.rm = TRUE)[2]), -->
<!--                  by = 2 -->
<!--     ) -->
<!--   ) + -->
<!--   # linetype: -->
<!--   scale_linetype_manual( -->
<!--     name = "Vertebrate host biting tolerance\n(bites per host per day)", -->
<!--     values = c("solid", "longdash", "dotted"), -->
<!--     breaks = c(10, 50, Inf), -->
<!--     labels = unname(c("10 (Chitnis)", "50 (Chitnis)", TeX("$\\infty$ (Ross-Macdonald)"))) -->
<!--   ) + -->
<!--   # color: -->
<!--   scale_colour_manual( -->
<!--     name = "Thermal extrema", -->
<!--     breaks = c("CTmax", "CTmin", "VTTR"), -->
<!--     labels = c("Critical maximum", "Critical minimum", "Mosquito thermal\ntolerance range"), -->
<!--     values = c("red", "blue", "grey"), -->
<!--     guide = guide_legend(keyheight = unit(40, "cm")) -->
<!--   ) + -->

<!--   # faceting: -->
<!--   facet_wrap(~system_label, -->
<!--              scales = "free", -->
<!--              nrow = 2, -->
<!--              labeller = labeller() -->
<!--   ) + -->

<!--   # legend: -->
<!--   guides( -->
<!--     color = guide_legend( -->
<!--       override.aes = list(size = 4), -->
<!--       order = 1 -->
<!--     ), -->
<!--     linetype = guide_legend( -->
<!--       keywidth = 4, -->
<!--       order = 2 -->
<!--     ), -->
<!--   ) + -->

<!--   # theme options: -->
<!--   theme_minimal_hgrid(11) + -->
<!--   theme( -->
<!--     axis.title.x = element_text(hjust = 0.5), -->
<!--     strip.text = ggtext::element_markdown( -->
<!--       size = 11, -->
<!--       hjust = 0 -->
<!--     ) -->
<!--   ) -->

<!-- # Plot -->
<!-- shift_legend(CTRange_plots) -->
<!-- ``` -->

<!-- ```{r fig-S7_CH_Range, dev = c('pdf','svg', 'png'), message=FALSE, out.width='100%', fig.width=9, fig.height=6, fig.align='center', fig.cap='\\label{fig:CH_Range} Critical community sizes as a function of temperature and biting tolerance.'} -->

<!-- # x = vertebrate host population density -->
<!-- # y = Temperature -->
<!-- # linetype = vertebrate host biting tolerance (needs to vary from "zero to infinity") -->
<!-- # curves: -->
<!-- #   CH_min - blue -->
<!-- #   CH_max - red -->
<!-- #   VTTR - black -->

<!-- # build data frame for plotting -->
<!-- CHRange_df <- AllOutputs %>% -->
<!--   ungroup() %>% -->
<!--   # Arrange along the plotting variables -->
<!--   select(system_label, Temperature, sigmaH, CHmax, CHmin) %>% -->
<!--   filter(sigmaH %in% c(10, 50, 100)) %>% -->
<!--   filter(is.finite(CHmax)) %>% -->
<!--   filter(CHmin > 0) %>% -->
<!--   distinct() %>% -->
<!--   # Arrange along the plotting variables -->
<!--   arrange(system_label, Temperature, sigmaH, CHmax, CHmin) %>% -->
<!--   melt(id = c("system_label", "Temperature", "sigmaH")) %>% -->
<!--   arrange(Temperature, sigmaH) -->


<!-- CHRange_plots <- CHRange_df %>% -->
<!--   ## Set up plot ## -->
<!--   # x = threshold values, y = temperature, -->
<!--   # color = threshold type, line type = sigmaH -->
<!--   ggplot(aes( -->
<!--     x = value, y = Temperature, -->
<!--     color = variable, linetype = as.factor(sigmaH) -->
<!--   )) + -->

<!--   # mosquito thermal tolerance range curves: -->
<!--   geom_hline( -->
<!--     data = MosqThermRange_df, -->
<!--     aes(yintercept = CTmin_V0, colour = "VTTR"), -->
<!--     lwd = 1 -->
<!--   ) + -->
<!--   geom_hline( -->
<!--     data = MosqThermRange_df, -->
<!--     aes(yintercept = CTmax_V0, colour = "VTTR"), -->
<!--     lwd = 1 -->
<!--   ) + -->

<!--   # CH threshold curves: -->
<!--   geom_path( -->
<!--     data = filter(CHRange_df, variable == "CHmin" & is.finite(sigmaH)), -->
<!--     lwd = 1 -->
<!--   ) + -->
<!--   geom_path( -->
<!--     data = filter(CHRange_df, variable == "CHmax"), -->
<!--     lwd = 1 -->
<!--   ) + -->

<!--   # x-axis: log10-scaled with no buffer-space -->
<!--   scale_x_log10( -->
<!--     name = TeX("Vertebrate host population density"), -->
<!--     expand = c(0, 0), -->
<!--     limits = c(0.01, 2E5), -->
<!--     breaks = 10^seq(-2, 5), -->
<!--     labels = TeX(c("$0.01$", "$0.1$", "$1$", "$10$", "$100$", "$10^3$", "$10^4$", "$10^5$")) -->
<!--   ) + -->
<!--   # y-axis: -->
<!--   scale_y_continuous( -->
<!--     name = expression("Temperature "(degree * C)), -->
<!--     expand = c(0.05, 0.05), -->
<!--     limits = range(CHRange_df$Temperature), -->
<!--     breaks = seq(floor(range(CHRange_df$Temperature)[1]), -->
<!--                  floor(range(CHRange_df$Temperature)[2]), -->
<!--                  by = 2 -->
<!--     ) -->
<!--   ) + -->
<!--   # linetype: -->
<!--   scale_linetype_manual( -->
<!--     name = "Biting tolerance\n(bites per host per day)", -->
<!--     values = c("solid", "longdash", "dotdash"), -->
<!--     breaks = c(10, 50, 100) -->
<!--   ) + -->

<!--   # color: -->
<!--   scale_colour_manual( -->
<!--     name = "Threshold type", -->
<!--     values = c("red", "blue", "grey"), -->
<!--     breaks = c("CHmax", "CHmin", "VTTR"), -->
<!--     labels = c("Maximum community size", "Minimum community size", "Mosquito thermal niche") -->
<!--   ) + -->

<!--   # faceting: -->
<!--   facet_wrap(~system_label, scales = "free", nrow = 2) + -->


<!--   # legend: -->
<!--   guides( -->
<!--     color = guide_legend( -->
<!--       override.aes = list(size = 4), -->
<!--       order = 1 -->
<!--     ), -->
<!--     linetype = guide_legend( -->
<!--       keywidth = 4, -->
<!--       order = 2 -->
<!--     ), -->
<!--   ) + -->
<!--   # theme options: -->
<!--   theme_minimal_vgrid(11) + -->
<!--   theme( -->
<!--     legend.box = "vertical", -->
<!--     legend.position = "bottom", -->
<!--     legend.margin = margin(0, 0, 0, 0), -->
<!--     legend.text = ggtext::element_markdown(), -->
<!--     legend.title = element_text(size = 11), -->
<!--     legend.direction = "vertical", -->
<!--     axis.title.x = element_text(hjust = 0.5), -->
<!--     strip.text = ggtext::element_markdown( -->
<!--       size = 11, -->
<!--       hjust = 0, -->
<!--       padding = margin(0, 0, 0, 0), -->
<!--       margin = margin(1, 1, 1, 1) -->
<!--     ) -->
<!--   ) -->

<!-- # Plot -->
<!-- shift_legend(CHRange_plots) -->
<!-- ``` -->

```{r table-2_Toptdiffbound, dev = c('pdf','svg', 'png'), message=FALSE, out.width='100%', fig.width=9, fig.height=6, fig.align='center', fig.cap='\\label{fig:Toptdiffbound} Calculating how large the difference between the Ross-Macdonald and Chitnis Topt estimates can be.'}
# Estimating the difference between Topt and Topt_RM numerically using our previous data
Toptdiff_CCH <- data.Topt %>%
  ungroup() %>%
  select(system_ID, sigmaH, KH, median) %>%
  rename(Topt = median) %>%
  filter(is.finite(sigmaH)) %>%
  distinct()

Toptdiff_RM <- data.Topt %>%
  ungroup() %>%
  filter(is.infinite(sigmaH)) %>%
  select(system_ID, KH, median) %>%
  rename(Topt_RM = median) %>%
  distinct()

Toptdiff_df <- left_join(Toptdiff_CCH, Toptdiff_RM) %>%
  mutate(Toptdiff = Topt_RM - Topt) %>%
  mutate(absToptdiff = abs(Toptdiff)) %>%
  mutate(propToptdiff = (Topt_RM - Topt) / Topt_RM) %>%
  mutate(sigmaHKH = sigmaH * KH) %>%
  group_by(system_ID) %>%
  filter(absToptdiff == max(absToptdiff)) %>%
  select(-sigmaH, -KH, -sigmaHKH, -absToptdiff) %>%
  distinct()


# Calculating Topt0 using the "simplified" equation
Topt0_df <- median.Vec %>%
  filter(V0 > 1) %>%
  mutate(muV = 1 / (lf + eps)) %>%
  mutate(P_EIP = exp(-muV / etaV)) %>%
  mutate(proxy_0 = lf * betaV * P_EIP / (KL * rhoL * (lf - 1 / (sigmaV_f * deltaL)))) %>%
  select(system_ID, Temperature, proxy_0) %>%
  group_by(system_ID)

test_plot <- Topt0_df %>%
  ggplot(aes(x = Temperature, y = proxy_0)) +
  geom_point() +
  facet_wrap(~system_ID, scales = "free")
test_plot

Topt0_base_estimates <- Topt0_df %>%
  group_by(system_ID) %>%
  # Calculate Topt_0
  filter(proxy_0 == proxy_0[which.max(proxy_0)]) %>%
  rename(Topt_0 = Temperature)
# check with above: Topt_0 matches with Topt when sigmaH*KH is minimized
# also shows that these estimates are independent of KL (and thus ABSOLUTE adult mosquito density)

# Calculating Topt0 using the "simplified" equation
ToptRM_df <- median.Vec %>%
  mutate(muV = 1 / (lf + eps)) %>%
  mutate(P_EIP = exp(-muV / etaV)) %>%
  mutate(proxy_RM = sigmaV^2 * V0 * betaV * P_EIP / muV) %>%
  select(system_ID, Temperature, proxy_RM) %>%
  group_by(system_ID)

ToptRM_base_estimates <- data.Topt %>%
  group_by(system_ID) %>%
  filter(is.infinite(sigmaH)) %>%
  select(system_ID, median) %>%
  rename(Topt_RM = median) %>%
  distinct()
# Calculate Topt_RM
# filter(proxy_RM == proxy_RM[which.max(proxy_RM)]) %>%
# rename(Topt_RM = Temperature)
# check with above: Topt_RM matches with Topt when sigmaH*KH is maximized
# also shows that these estimates are independent of KL (and thus ABSOLUTE adult mosquito density)

Topt_estimates_median <- left_join(ToptRM_base_estimates, Topt0_base_estimates) %>%
  select(system_ID, Topt_RM, Topt_0) %>%
  mutate(Topt_diff = Topt_RM - Topt_0) %>%
  mutate(prop_Topt_diff = abs(Topt_diff) / Topt_RM)


# Investigating Topt_RM and Topt_0 further

test_df <- median.Vec %>%
  mutate(muV = 1 / (lf + eps)) %>%
  mutate(P_EIP = exp(-muV / etaV)) %>%
  mutate(sigmaVV0 = sigmaV * V0) %>%
  mutate(proxy_0 = betaV * P_EIP / (muV * V0)) %>%
  mutate(proxy_RM = sigmaV^2 * V0 * betaV * P_EIP / muV) %>% # = sigmaVV0^2*proxy_0
  filter(is.finite(proxy_0)) %>%
  select(system_ID, Temperature, proxy_RM, proxy_0, sigmaVV0)
```

```{r fig-SX_CT_distributions, dev = c('pdf','svg', 'png'), message=FALSE, out.width='100%', fig.width=9, fig.height=6, fig.align='center', fig.cap='\\label{fig:CT_dists} The distributions of the critical thermal minimum, critical thermal maximum, and thermal optimum vary with vertebrate host availability.'}
all.density.df <- read_rds("results/CTminmaxTopt_densities.rds") %>%
  ungroup() %>%
  mutate(system_label = case_when(
    system_ID == "Aedes aegypti / DENV" ~ "(a) *Ae. aegypti* and DENV",
    system_ID == "Aedes aegypti / ZIKV" ~ "(b) *Ae. aegypti* and ZIKV",
    system_ID == "Aedes albopictus / DENV" ~ "(c&#41; *Ae. albopictus* and DENV",
    system_ID == "Anopheles gambiae / Plasmodium falciparum" ~ "(d) *An. gambiae* and *P. falciparum*",
    system_ID == "Culex quinquefasciatus / WNV" ~ "(e) *Cx. quinquefasciatus* and WNV"
  ))

### Option 1: inline violin plots ----
plot.densities_violin_inline <- ggplot() +
  geom_violin(
    data = filter(all.density.df, variable == "Thermal optimum"),
    aes(x = value, y = KH_factor, linetype = sigmaH, fill = "Topt")
  ) +
  geom_violin(
    data = filter(all.density.df, variable == "Critical thermal minimum"),
    aes(x = value, y = KH_factor, linetype = sigmaH, fill = "CTmin"),
  ) +
  geom_violin(
    data = filter(all.density.df, variable == "Critical thermal maximum"),
    aes(x = value, y = KH_factor, linetype = sigmaH, fill = "CTmax"),
  ) +
  scale_x_continuous(
    name = "Temperature (°C)",
    expand = c(0, 0)
  ) +
  scale_y_discrete(
    name = "Vertebrate host population density (ind/ha)"
  ) +
  scale_linetype(
    name = "Biting tolerance\n(bites per host per day)"
  ) +
  scale_fill_discrete(
    name = "",
    breaks = c("CTmin", "Topt", "CTmax"),
    labels = c("Critical thermal minimum", "Thermal optimum", "Critical thermal maximum")
  ) +
  facet_wrap(~system_label, labeller = labeller()) +
  theme_minimal_grid(16) +
  theme(
    legend.margin = margin(0, 0, 0, 0),
    legend.title = element_text(size = 10),
    axis.title.x = element_text(hjust = 0.5),
    strip.text = ggtext::element_markdown(
      size = 11,
      hjust = 0,
      padding = margin(0, 0, 0, 0),
      margin = margin(1, 1, 1, 1)
    )
  )
shift_legend(plot.densities_violin_inline)

### Option 2: inline box and whisker plots ----
plot.densities_boxwhisker_inline <- ggplot() +
  geom_boxplot(
    data = filter(all.density.df, variable == "Thermal optimum"),
    aes(x = value, y = KH_factor, linetype = sigmaH, fill = "Topt")
  ) +
  geom_boxplot(
    data = filter(all.density.df, variable == "Critical thermal minimum"),
    aes(x = value, y = KH_factor, linetype = sigmaH, fill = "CTmin"),
  ) +
  geom_boxplot(
    data = filter(all.density.df, variable == "Critical thermal maximum"),
    aes(x = value, y = KH_factor, linetype = sigmaH, fill = "CTmax"),
  ) +
  scale_x_continuous(
    name = "Temperature (°C)",
    expand = c(0, 0)
  ) +
  scale_y_discrete(
    name = "Vertebrate host population density (ind/ha)"
  ) +
  scale_linetype(
    name = "Biting tolerance\n(bites per host per day)"
  ) +
  scale_fill_discrete(
    name = "",
    breaks = c("CTmin", "Topt", "CTmax"),
    labels = c("Critical thermal minimum", "Thermal optimum", "Critical thermal maximum")
  ) +
  facet_wrap(~system_label, labeller = labeller()) +
  theme_minimal_grid(16) +
  theme(
    legend.margin = margin(0, 0, 0, 0),
    legend.title = element_text(size = 10),
    axis.title.x = element_text(hjust = 0.5),
    strip.text = ggtext::element_markdown(
      size = 11,
      hjust = 0,
      padding = margin(0, 0, 0, 0),
      margin = margin(1, 1, 1, 1)
    )
  )
shift_legend(plot.densities_boxwhisker_inline)

### Option 3: stacked violin plots ----
plot.densities_violin_stacked <- ggplot() +
  geom_violin(
    data = all.density.df,
    aes(x = value, y = KH_factor, fill = variable, linetype = sigmaH)
  ) +
  scale_x_continuous(
    name = "Temperature (°C)",
    expand = c(0, 0)
  ) +
  scale_y_discrete(
    name = "Vertebrate host population density (ind/ha)"
  ) +
  scale_linetype(
    name = "Biting tolerance\n(bites per host per day)"
  ) +
  scale_fill_discrete(
    name = ""
  ) +
  facet_wrap(~system_label, labeller = labeller()) +
  theme_minimal_grid(16) +
  theme(
    legend.margin = margin(0, 0, 0, 0),
    legend.title = element_text(size = 10),
    axis.title.x = element_text(hjust = 0.5),
    strip.text = ggtext::element_markdown(
      size = 11,
      hjust = 0,
      padding = margin(0, 0, 0, 0),
      margin = margin(1, 1, 1, 1)
    )
  )
shift_legend(plot.densities_violin_stacked)

### Option 4: stacked box and whisker plots ----
plot.densities_boxwhisker_stacked <- ggplot() +
  geom_boxplot(
    data = all.density.df,
    aes(x = value, y = KH_factor, fill = variable, linetype = sigmaH)
  ) +
  scale_x_continuous(
    name = "Temperature (°C)",
    expand = c(0, 0)
  ) +
  scale_y_discrete(
    name = "Vertebrate host population density (ind/ha)"
  ) +
  scale_linetype(
    name = "Biting tolerance\n(bites per host per day)"
  ) +
  scale_fill_discrete(
    name = ""
  ) +
  facet_wrap(~system_label, labeller = labeller()) +
  theme_minimal_grid(16) +
  theme(
    legend.margin = margin(0, 0, 0, 0),
    legend.title = element_text(size = 10),
    axis.title.x = element_text(hjust = 0.5),
    strip.text = ggtext::element_markdown(
      size = 11,
      hjust = 0,
      padding = margin(0, 0, 0, 0),
      margin = margin(1, 1, 1, 1)
    )
  )
shift_legend(plot.densities_boxwhisker_stacked)
```

```{r fig-SX_R0_sensitivity, dev = c('pdf','svg', 'png'), message=FALSE, out.width='100%', fig.width=9, fig.height=6, fig.align='center', fig.cap='\\label{fig:R0_sens} The sensitivity of the distribution of $\\mathcal{R}_0$ to mosquito life history traits.'}
R0.HPD <- read_rds("results/R0_HPD_sens.rds") %>%
  ungroup() %>%
  mutate(system_label = case_when(
    system_ID == "Aedes aegypti / DENV" ~ "(a) *Ae. aegypti* and DENV",
    system_ID == "Aedes aegypti / ZIKV" ~ "(b) *Ae. aegypti* and ZIKV",
    system_ID == "Aedes albopictus / DENV" ~ "(c&#41; *Ae. albopictus* and DENV",
    system_ID == "Anopheles gambiae / Plasmodium falciparum" ~ "(d) *An. gambiae* and *P. falciparum*",
    system_ID == "Culex quinquefasciatus / WNV" ~ "(e) *Cx. quinquefasciatus* and WNV"
  ))

# Label functions:
appender_sigmaH <- function(string) {
  unname(TeX(paste("$\\sigma_H = $", string)))
}
appender_KH <- function(string) {
  unname(TeX(paste("$K_H = $", string)))
}

Temp_range_for_plot <- R0.HPD %>%
  ungroup() %>%
  dplyr::filter(rel_HPD_width > eps) %>%
  select(Temperature) %>%
  range()

plot.R0.rel.sens <- R0.HPD %>%
  filter(KH %in% c(1, 100) & sigmaH %in% c(50, Inf)) %>%
  filter(!(KH == 100 & sigmaH == Inf)) %>%
  filter(rel_HPD_width != 0) %>%
  # For each KH value, sum up all sensitivity values to get total sensitivity across parameters
  group_by(system_ID, sigmaH, KH, Temperature) %>%
  mutate(sens_total = sum(rel_HPD_width)) %>%
  # Divide each sensitivity value by the total sensitivity
  mutate(sens_rel = rel_HPD_width / sens_total) %>%
  arrange(sens_rel) %>%
  # Make a stacked plot, colored by parameter
  ggplot(aes(x = Temperature, y = sens_rel, fill = focal_var)) +
  geom_area() +
  scale_fill_discrete(
    name = "Focal parameter",
    breaks = c("betaV", "deltaL", "etaV", "muV", "rhoL", "sigmaV", "sigmaV_f"),
    labels = c(
      "Vector competence", "Pr(larval survival)",
      "Parasite development rate", "Mortality rate",
      "Immature development rate", "Max. biting rate",
      "Eggs per female per day"
    )
  ) +
  scale_x_continuous(
    limits = Temp_range_for_plot,
    expand = c(0, 0)
  ) +
  scale_y_continuous(
    name = unname(TeX("Relative contribution to $R_0$ HPD width"))
  ) +
  facet_grid(
    cols = vars(system_label),
    rows = vars(KH, sigmaH),
    labeller = labeller(
      system_label = label_wrap_gen(width = 10),
      sigmaH = as_labeller(appender_sigmaH, default = label_parsed),
      KH = as_labeller(appender_KH, default = label_parsed)
    ),
    scales = "free_y"
  ) +
  theme_minimal_hgrid(16) +
  theme(
    legend.margin = margin(0, 0, 0, 0),
    legend.title = element_text(size = 10),
    legend.text = element_text(size = 10),
    axis.title.x = element_text(hjust = 0.5),
    strip.text.x = ggtext::element_markdown(
      size = 11,
      hjust = 0,
      padding = margin(0, 0, 0, 0),
      margin = margin(1, 1, 1, 1)
    )
  )
plot.R0.rel.sens
# shift_legend(plot.R0.rel.sens)
```

```{r fig-SX_ddTR0_sensitivity, dev = c('pdf','svg', 'png'), message=FALSE, out.width='100%', fig.width=9, fig.height=6, fig.align='center', fig.cap='\\label{fig:ddTR0_sens} The sensitivity of the distribution of the derivative of $\\mathcal{R}_0$ with respect to temperature to mosquito life history traits.'}
ddTR0.HPD <- read_rds("results/ddTR0_HPD_sens.rds") %>%
  ungroup() %>%
  mutate(system_label = case_when(
    system_ID == "Aedes aegypti / DENV" ~ "(a) *Ae. aegypti* and DENV",
    system_ID == "Aedes aegypti / ZIKV" ~ "(b) *Ae. aegypti* and ZIKV",
    system_ID == "Aedes albopictus / DENV" ~ "(c&#41; *Ae. albopictus* and DENV",
    system_ID == "Anopheles gambiae / Plasmodium falciparum" ~ "(d) *An. gambiae* and *P. falciparum*",
    system_ID == "Culex quinquefasciatus / WNV" ~ "(e) *Cx. quinquefasciatus* and WNV"
  ))

## Plot R0 uncertainty
Temp_range_for_plot <- ddTR0.HPD %>%
  ungroup() %>%
  dplyr::filter(HPD_width > eps) %>%
  select(Temperature) %>%
  range()

var_name_table <- list(
  betaV = c(TeX("$\\beta_V$")),
  deltaL = c(TeX("$\\delta_L$")),
  etaV = c(TeX("$\\eta_V$")),
  muV = c(TeX("$\\mu_V$")),
  rhoL = c(TeX("$\\rho_L$")),
  sigmaV = c(TeX("$\\sigma_V$")),
  sigmaV_f = c(TeX("$\\sigma_v f$"))
)

plot.ddTR0.rel.sens <- ddTR0.HPD %>%
  filter(KH %in% c(1, 100) & sigmaH %in% c(50, Inf)) %>%
  filter(!(KH == 100 & sigmaH == Inf)) %>%
  filter(rel_HPD_width != 0) %>%
  # For each KH value, sum up all sensitivity values to get total sensitivity across parameters
  group_by(system_ID, sigmaH, KH, Temperature) %>%
  mutate(sens_total = sum(rel_HPD_width)) %>%
  # Divide each sensitivity value by the total sensitivity
  mutate(sens_rel = rel_HPD_width / sens_total) %>%
  arrange(sens_rel) %>%
  # Make a stacked plot, colored by parameter
  ggplot(aes(x = Temperature, y = sens_rel, fill = focal_var)) +
  geom_area() +
  scale_fill_discrete(
    name = "Focal parameter",
    breaks = c("betaV", "deltaL", "etaV", "muV", "rhoL", "sigmaV", "sigmaV_f"),
    labels = c(
      "Vector competence", "Pr(larval survival)",
      "Parasite development rate", "Mortality rate",
      "Immature development rate", "Max. biting rate",
      "Eggs per female per day"
    )
  ) +
  scale_x_continuous(
    limits = Temp_range_for_plot,
    expand = c(0, 0)
  ) +
  scale_y_continuous(
    name = unname(TeX("Relative contribution to $dR_0/dT$ HPD width"))
  ) +
  facet_grid(
    cols = vars(system_label),
    rows = vars(KH, sigmaH),
    labeller = labeller(
      system_label = label_wrap_gen(width = 10),
      sigmaH = as_labeller(appender_sigmaH, default = label_parsed),
      KH = as_labeller(appender_KH, default = label_parsed)
    ),
    scales = "free_y"
  ) +
  theme_minimal_hgrid(16) +
  theme(
    legend.margin = margin(0, 0, 0, 0),
    legend.title = element_text(size = 10),
    legend.text = element_text(size = 10),
    axis.title.x = element_text(hjust = 0.5),
    strip.text.x = ggtext::element_markdown(
      size = 11,
      hjust = 0,
      padding = margin(0, 0, 0, 0),
      margin = margin(1, 1, 1, 1)
    )
  )
plot.ddTR0.rel.sens
```
```{r fig-SX_Topt_sensitivity, dev = c('pdf','svg', 'png'), message=FALSE, out.width='100%', fig.width=9, fig.height=6, fig.align='center', fig.cap='\\label{fig:Topt_sens} The sensitivity of the thermal optimmum to mosquito life history traits as a function of vertebrate host population density when $\\sigma_H = 50$.'}
Topt.HPD <- read_rds("results/Topt_HPD_sens.rds") %>%
  ungroup() %>%
  mutate(system_label = case_when(
    system_ID == "Aedes aegypti / DENV" ~ "(a) *Ae. aegypti* and DENV",
    system_ID == "Aedes aegypti / ZIKV" ~ "(b) *Ae. aegypti* and ZIKV",
    system_ID == "Aedes albopictus / DENV" ~ "(c&#41; *Ae. albopictus* and DENV",
    system_ID == "Anopheles gambiae / Plasmodium falciparum" ~ "(d) *An. gambiae* and *P. falciparum*",
    system_ID == "Culex quinquefasciatus / WNV" ~ "(e) *Cx. quinquefasciatus* and WNV"
  )) %>%
  filter(!is.na(rel_HPD_width)) %>%
  # For each KH value, sum up all sensitivity values to get total sensitivity
  group_by(system_ID, sigmaH, KH) %>%
  mutate(sens_total = sum(rel_HPD_width)) %>%
  # Divide each sensitivity value by the total sensitivity
  mutate(sens_rel = rel_HPD_width / sens_total) # %>%
# arrange(sens_rel)

# !!! mention the value of sigmaH

plot.Topt.rel.sens <- Topt.HPD %>%
  # Make a stacked plot, colored by parameter
  ggplot(aes(x = KH, y = sens_rel, fill = focal_var)) +
  geom_area() +
  scale_fill_discrete(
    name = "Focal parameter",
    breaks = c("betaV", "deltaL", "etaV", "muV", "rhoL", "sigmaV", "sigmaV_f"),
    labels = c(
      "Vector competence", "Pr(larval survival)",
      "Parasite development rate", "Mortality rate",
      "Immature development rate", "Max. biting rate",
      "Eggs per female per day"
    )
  ) +
  scale_x_log10(
    name = TeX("Vertebrate host population density (ind/ha)"),
    expand = c(0, 0),
    limits = c(0.05, 1E3),
    breaks = 10^seq(-2, 4, 1),
    labels = TeX(c("$0.01$", "$0.1$", "$1$", "$10", "$100$", "$10^3$", "$10^4$"))
  ) +
  scale_y_continuous(
    name = unname(TeX("Relative contribution to $T_{opt}$ HPD width"))
  ) +
  # scale_y_continuous(
  #   limits = c(0,1)
  # ) +
  facet_wrap(~system_label, scales = "free") +
  theme_minimal_hgrid(16) +
  theme(
    legend.margin = margin(0, 0, 0, 0),
    legend.title = element_text(size = 10),
    legend.text = element_text(size = 10),
    axis.title.x = element_text(hjust = 0.5),
    strip.text.x = ggtext::element_markdown(
      size = 11,
      hjust = 0,
      padding = margin(0, 0, 0, 0),
      margin = margin(1, 1, 1, 1)
    )
  )
shift_legend(plot.Topt.rel.sens)
```
